# ESO: ExternalSecret resource to sync the Postgres admin password from Vault to a Kubernetes Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planescape-postgres-admin
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: planescape-postgres-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/planescape/postgres
        property: password 