# ESO: ExternalSecret to sync Jenkins admin credentials from Vault to K8s Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planescape-jenkins-admin
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: planescape-jenkins-admin
    creationPolicy: Owner
  data:
    - secretKey: jenkins-admin-user
      remoteRef:
        key: secret/data/planescape/jenkins
        property: username
    - secretKey: jenkins-admin-password
      remoteRef:
        key: secret/data/planescape/jenkins
        property: password
