# Vault/ESO: ClusterSecretStore resource for ESO to authenticate to Vault using Kubernetes auth
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://{{ include "planescape.fullname" . }}-vault.{{ .Release.Namespace }}.svc.cluster.local:8200"
      path: ""
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: eso
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system 