# Vault: Job to setup Kubernetes authentication method
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "planescape.fullname" . }}-vault-auth-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: vault-init
      containers:
        - name: vault-auth-setup
          image: hashicorp/vault:1.15.2
          env:
            - name: VAULT_ADDR
              value: "http://{{ include "planescape.fullname" . }}-vault.{{ .Release.Namespace }}.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: "root"
          command:
            - /bin/sh
            - -c
            - |
              # Wait for Vault to be up and running
              for i in $(seq 1 60); do
                vault status && break
                sleep 5
              done
              
              # Enable Kubernetes authentication method
              vault auth enable kubernetes || true
              
              # Configure Kubernetes authentication
              vault write auth/kubernetes/config \
                token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
                kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" \
                kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              
              # Create basic ESO role with default policy (will be updated later by eso-policy job)
              vault write auth/kubernetes/role/eso \
                bound_service_account_names=external-secrets \
                bound_service_account_namespaces=external-secrets-system \
                policies=default \
                ttl=1h
      automountServiceAccountToken: true 