# Vault: ServiceAccount, Role, and RoleBinding for vault-init and vault-eso-policy jobs to read secrets and exec into pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "planescape.labels" . | nindent 4 }}
    component: vault-init
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "planescape.labels" . | nindent 4 }}
    component: vault-init
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods", "pods/exec"]
    verbs: ["get", "list", "create"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list"]
  # Additional permissions for proper job execution
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "planescape.labels" . | nindent 4 }}
    component: vault-init
subjects:
  - kind: ServiceAccount
    name: vault-init
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: vault-init
  apiGroup: rbac.authorization.k8s.io 