# Vault: Job to create ESO policy for token-based authentication
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "planescape.fullname" . }}-vault-eso-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "planescape.labels" . | nindent 4 }}
    component: vault-setup
spec:
  template:
    metadata:
      labels:
        {{- include "planescape.labels" . | nindent 8 }}
        component: vault-setup
    spec:
      restartPolicy: OnFailure
      serviceAccountName: vault-init
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: vault-eso-policy
          image: hashicorp/vault:1.15.2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: VAULT_ADDR
              value: "http://{{ include "planescape.fullname" . }}-vault.{{ .Release.Namespace }}.svc.cluster.local:8200"
            - name: VAULT_TOKEN
              value: {{ .Values.planescape.vault.token | quote }}
          command:
            - /bin/sh
            - -c
            - |
              echo "Setting up ESO policy for token-based authentication..."
              
              # Wait for Vault to be ready
              echo "Waiting for Vault to be ready..."
              for i in $(seq 1 60); do
                if vault status >/dev/null 2>&1; then
                  echo "Vault is ready!"
                  break
                fi
                echo "Waiting for Vault... ($i/60)"
                sleep 3
              done
              
              echo "Creating ESO policy for token authentication..."
              vault policy write eso-policy /vault/policies/vault-eso-policy.hcl
              
              echo "ESO policy setup completed successfully!"
          volumeMounts:
            - name: eso-policy
              mountPath: /vault/policies
              readOnly: true
      volumes:
        - name: eso-policy
          configMap:
            name: {{ include "planescape.fullname" . }}-vault-eso-policy
      automountServiceAccountToken: true 