# ESO: Service Account Token Secret for external-secrets service account
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-token
  namespace: external-secrets-system
  annotations:
    kubernetes.io/service-account.name: external-secrets
type: kubernetes.io/service-account-token 