# External Secrets: Vault token secret for ESO authentication
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets-system
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.vault.token | b64enc | quote }} 