apiVersion: v2
name: external-secrets
description: External Secrets Operator for Planescape platform
type: application
version: 0.1.0
appVersion: "0.17.0"

dependencies:
  - name: external-secrets
    version: 0.17.0
    repository: https://charts.external-secrets.io 