apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth-config
  namespace: vault
data:
  config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kubernetes.default.svc
      name: k8s
    contexts:
    - context:
        cluster: k8s
        user: vault-auth
      name: vault-auth
    current-context: vault-auth
    users:
    - name: vault-auth
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token 