controller:
  serviceType: NodePort
  servicePort: 8080
  targetPort: 8080
  
  # High Availability configuration
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  # Resource configuration
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  # Persistence configuration
  persistence:
    enabled: true
    size: 8Gi
    storageClass: standard
    accessMode: ReadWriteOnce

  # Security context
  securityContext:
    runAsUser: 1000
    fsGroup: 1000

  # Jenkins configuration
  installPlugins:
    - kubernetes:1.31.3
    - workflow-aggregator:2.6
    - git:4.11.0
    - configuration-as-code:1.55
    - blueocean:1.25.3
    - pipeline-model-definition:1.9.3
    - pipeline-stage-view:2.19
    - pipeline-github:2.7
    - pipeline-utility-steps:2.13.0
    - credentials-binding:1.27
    - timestamper:1.18
    - ws-cleanup:0.45
    - ansicolor:1.0.2

  # Jenkins system configuration
  systemMessage: "Jenkins configured automatically by Helm"
  numExecutors: 0  # We'll use Kubernetes agents instead

  # Kubernetes plugin configuration
  kubernetes:
    enabled: true
    namespace: jenkins-workers
    jenkinsUrl: http://jenkins:8080
    jenkinsTunnel: jenkins-agent:50000
    containerCapStr: "10"
    maxRequestsPerHostStr: "32"
    retentionTimeout: 5
    connectTimeout: 5
    readTimeout: 15

  # Ingress configuration (disabled for local)
  ingress:
    enabled: false

  # Admin user configuration
  adminUser: admin
  adminPassword: ""  # Will be set from secret

  # Additional secrets
  additionalSecrets:
    - name: jenkins-secret
      key: jenkins-admin-password
      secretName: jenkins-secret

  # Health checks
  livenessProbe:
    httpGet:
      path: /login
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    httpGet:
      path: /login
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  # Service account configuration
  serviceAccount:
    create: true
    name: jenkins
    annotations: {}

  # Network policies
  networkPolicy:
    enabled: true
    apiVersion: networking.k8s.io/v1
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                name: jenkins-workers
        ports:
          - protocol: TCP
            port: 50000
      - to:
          - namespaceSelector:
              matchLabels:
                name: planescape
        ports:
          - protocol: TCP
            port: 5432

# Agent configuration
agent:
  enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  serviceAccount:
    create: true
    name: jenkins-agent
    annotations: {} 