global:
  postgresql:
    auth:
      existingSecret: postgres-secret
      username: postgres
      database: planescape

primary:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: standard

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  service:
    type: ClusterIP
    port: 5432

  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  podSecurityContext:
    enabled: true
    fsGroup: 1001

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

volumePermissions:
  enabled: true 