apiVersion: planescape.io/v1alpha1
kind: PlanescapeJob
metadata:
  name: demo-job
  namespace: planescape-system
  labels:
    stack.planescape.io/name: demo-stack
    job.planescape.io/type: database-test
spec:
  schedule: "@once"  # Run once immediately
  vault:
    enabled: true
    role: "demo-stack-job-role"
    path: "database/creds/demo-stack-postgresql"
    ttl: "1h"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: demo-job
            stack: demo-stack
        spec:
          containers:
          - name: postgres-test
            image: postgres:15-alpine
            command: ["sh", "-c"]
            args:
            - |
              echo "Testing PostgreSQL connection..."
              # Wait for Vault agent to inject secrets
              while [ ! -f /vault/secrets/creds ]; do
                echo "Waiting for Vault secrets..."
                sleep 2
              done
              
              # Source the credentials
              source /vault/secrets/creds
              
              # Test the connection
              PGPASSWORD=$password psql -h demo-stack-postgresql -U $username -d planescape -c "SELECT version();"
              
              echo "Connection test completed successfully!"
            env:
            - name: PGCONNECT_TIMEOUT
              value: "10"
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
            securityContext:
              runAsNonRoot: true
              runAsUser: 999
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
          volumes:
          - name: tmp
            emptyDir: {}
          restartPolicy: Never 