apiVersion: planescape.io/v1alpha1
kind: PlanescapeJob
metadata:
  name: daily-backup-job
  namespace: planescape-system
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:15-alpine
            command: ["/bin/sh"]
            args:
            - -c
            - |
              echo "Starting daily backup at $(date)"
              # Backup logic would go here
              echo "Backup completed successfully"
            env:
            - name: PGHOST
              value: "postgresql"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "planescape"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
          restartPolicy: OnFailure 