apiVersion: planescape.io/v1alpha1
kind: PlanescapeJob
metadata:
  name: example-job
  namespace: planescape-system
spec:
  schedule: "@once"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example
            image: busybox:1.35
            command: ["echo", "Hello, World!"]
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
          restartPolicy: Never 