apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: planescape-helm-operator
rules:
# Core Planescape resources
- apiGroups:
  - planescape.io
  resources:
  - planescapestacks
  - planescapejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - planescape.io
  resources:
  - planescapestacks/status
  - planescapejobs/status
  verbs:
  - get
  - patch
  - update

# Core Kubernetes resources
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Apps resources
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Batch resources
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Networking resources
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Policy resources
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# RBAC resources
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Storage resources
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch

# Monitoring resources
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Vault resources
- apiGroups:
  - vault.hashicorp.com
  resources:
  - vaultauths
  - vaultconnections
  - vaultdynamicsecrets
  - vaultpkisecrets
  - vaultstaticsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# External Secrets Operator resources
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
  - clustersecretstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch 