# PostgreSQL Component Values

# Use the Bitnami PostgreSQL chart
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 15.3.0-debian-11-r0
  pullPolicy: IfNotPresent

# Global PostgreSQL settings
global:
  postgresql:
    auth:
      # Credentials will be loaded from secret
      existingSecret: postgres-secret
      username: postgres
      database: planescape
      # No password here - it comes from the secret

# Primary PostgreSQL instance
primary:
  # Persistence configuration
  persistence:
    enabled: true
    # Size and storage class will be overridden by environment
    size: 8Gi
    storageClass: standard
    accessMode: ReadWriteOnce

  # Resource configuration
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  # Service configuration
  service:
    type: ClusterIP
    port: 5432

  # Security context
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  # Pod security context
  podSecurityContext:
    enabled: true
    fsGroup: 1001

  # Metrics for monitoring
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  # Health checks
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

  # Network policy
  networkPolicy:
    enabled: true
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                name: planescape
        ports:
          - protocol: TCP
            port: 5432

  # Backup configuration
  backup:
    enabled: true
    schedule: "0 0 * * *"  # Daily at midnight
    retention: 7  # Keep backups for 7 days
    storage:
      size: 8Gi
      storageClass: standard

  # Maintenance
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  # Pod disruption budget
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

# Volume permissions
volumePermissions:
  enabled: true

# Service account
serviceAccount:
  create: true
  name: postgres
  annotations: {}

# Pod security context
podSecurityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

# Container security context
containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
      - ALL

# Labels and annotations
commonLabels:
  app: postgres
  component: database

commonAnnotations:
  gitops/component: postgres
  gitops/managed-by: helm 