apiVersion: planescape.io/v1alpha1
kind: PlanescapeStack
metadata:
  name: demo-stack
  namespace: planescape-system
  labels:
    environment: demo
    stack.planescape.io/type: development
spec:
  components:
    postgresql:
      enabled: true
      auth:
        database: "planescape"
        username: "postgres"
      primary:
        persistence:
          size: "8Gi"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        service:
          type: ClusterIP
          port: 5432
    jenkins:
      enabled: true
      controller:
        serviceType: ClusterIP
        persistence:
          size: "8Gi"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        installPlugins:
          - "kubernetes:1.31.3"
          - "workflow-aggregator:2.6"
          - "git:4.11.0"
          - "configuration-as-code:1.55"
          - "job-dsl:1.81"
          - "vault-plugin:3.20.1"
    vault:
      enabled: true
      server:
        ha:
          enabled: false
          replicas: 1
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        service:
          type: ClusterIP
        dataStorage:
          size: "10Gi" 