apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: planescapejobs.planescape.io
spec:
  group: planescape.io
  names:
    kind: PlanescapeJob
    listKind: PlanescapeJobList
    plural: planescapejobs
    singular: planescapejob
    shortNames:
      - pjob
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - jobTemplate
              properties:
                schedule:
                  type: string
                  description: "Schedule for the job. Use '@once' for one-time jobs or a cron expression for recurring jobs."
                concurrencyPolicy:
                  type: string
                  enum: [Allow, Forbid, Replace]
                  default: Forbid
                  description: "Specifies how to treat concurrent executions of a job."
                successfulJobsHistoryLimit:
                  type: integer
                  minimum: 0
                  default: 3
                  description: "The number of successful finished jobs to retain."
                failedJobsHistoryLimit:
                  type: integer
                  minimum: 0
                  default: 1
                  description: "The number of failed finished jobs to retain."
                jobTemplate:
                  type: object
                  required:
                    - spec
                  properties:
                    spec:
                      type: object
                      required:
                        - template
                      properties:
                        template:
                          type: object
                          required:
                            - spec
                          properties:
                            spec:
                              type: object
                              required:
                                - containers
                              properties:
                                containers:
                                  type: array
                                  items:
                                    type: object
                                    required:
                                      - name
                                      - image
                                    properties:
                                      name:
                                        type: string
                                      image:
                                        type: string
                                      command:
                                        type: array
                                        items:
                                          type: string
                                      args:
                                        type: array
                                        items:
                                          type: string
                                      env:
                                        type: array
                                        items:
                                          type: object
                                          properties:
                                            name:
                                              type: string
                                            value:
                                              type: string
                                            valueFrom:
                                              type: object
                                              properties:
                                                secretKeyRef:
                                                  type: object
                                                  required:
                                                    - name
                                                    - key
                                                  properties:
                                                    name:
                                                      type: string
                                                    key:
                                                      type: string
                                serviceAccountName:
                                  type: string
                                  description: "Name of the service account to use for Vault integration"
                                restartPolicy:
                                  type: string
                                  enum: [Never, OnFailure]
                                  default: Never
            status:
              type: object
              properties:
                active:
                  type: array
                  items:
                    type: object
                    required:
                      - kind
                      - name
                    properties:
                      kind:
                        type: string
                      name:
                        type: string
                lastScheduleTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Schedule
          type: string
          jsonPath: .spec.schedule
        - name: Concurrency
          type: string
          jsonPath: .spec.concurrencyPolicy
        - name: Last Schedule
          type: date
          jsonPath: .status.lastScheduleTime
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp 